Popup dialog
didierganthier/microverse-portfolio pull request #15
Opened 2022-09-06 22:39 UTC by didierganthier

### Popup Dialog
In this pull request we completed the following tasks:
- [x] Add structure and images to `index.html`
- [x] Add styles for the popup
- [x] Add Javascript interactions to show the popup
- [x] Add dynamic values for work

2022-09-06 23:12 UTC, phelian23 requested changes
Hi @didierganthier,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Following GitHub Flow
✔️ Following requirements
✔️ Descriptive PR Title
✔️ Descriptive PR Summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 23:12 UTC, phelian23 commented on index.html
>              <div class="work">
- [ ] As requested in the project requirements, The projects section should be created dynamically using Javascript. all already created HTML code for the projects section list should be removed, and instead, it should be added via JavaScript. You should only have a container for the section in the HTML file.

2022-09-06 23:12 UTC, phelian23 commented on style.css
> +    font-weight: 400;
- [ ] Kindly make sure that your design matches that of the template. the description, buttons, and technologies are not visible on the desktop version.
Your design
![Capture](https://user-images.githubusercontent.com/85095702/188755787-e0649a31-2135-4fa6-85d8-a4743b262190.PNG)
Figma template
![figma](https://user-images.githubusercontent.com/85095702/188755825-2cf7e993-779b-451c-9548-4b3eecc7ac9c.PNG)

2022-09-07 10:58 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @didierganthier 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job implementing the requirements by the previous reviewer ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 11:22 UTC, merged